name: Eval matrix

on:
  workflow_dispatch:

jobs:
  eval:
    name: Evaluate
    runs-on: ubuntu-latest
    strategy:
      matrix:
        pet: [dog, cat, mouse, bird, fish]

    environment:
      name: ${{ matrix.pet }}

    env:
      pet_type: ${{ matrix.pet }}
      pet_food: ${{ secrets.food }}

    steps:
      - name: Env
        run: env | sort

      - name: Echo
        run: |
          echo "A ${{ matrix.pet }} eats ${pet_food}."
