name: Eval matrix

on:
  workflow_dispatch:

jobs:
  eval:
    name: Evaluate
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - pet: cat
            name: Scratchy
          - pet: mouse
            name: Itchy

    env:
      pet_type: ${{ matrix.pet }}
      pet_name: ${{ matrix.name }}

    steps:
      - name: Env
        run: env | sort
