name: Run on PR's

on:
  pull_request:
  push:

jobs:
  init:
    name: Init steps
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'pull_request' }}

    steps:
      - name: Show env
        run: env | sort
