name: Run on PR's

on:
  pull_request:
  push:

jobs:
  init:
    name: PR steps
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'pull_request' }}

    steps:
      - name: Show env
        run: env | sort

      - name: Verify dev PR to prod
        if: ${{ github.base_ref == 'prod' }}
        run: |
          if [[ "$GITHUB_HEAD_REF" != 'dev' ]]
          then
            echo "ERROR: Only PR's from dev branch are allowed." 1>&2
            exit 1
          fi
