name: Run on PR's

on:
  pull_request:
  push:

jobs:
  init:
    name: Init steps
    runs-on: ubuntu-latest
    if: ${{ env.GITHUB_EVENT_NAME == "pull_request" }}

    steps:
      - name: Show env
        run: env | sort
